### ISSUE TITLE
Jenkins Exporter fails if one of the statuses is not present

### ISSUE THREAD

**Issue by ashishjain14** [lovoo/jenkins_exporter#4]
If we create a brand new pipeline in jenkins and try to run the exporter it fails. This is because none of the statuses are currently part of job data returned  by jenkins.  I hit the following failure in one of use cases
Exception happened during processing of request from ('127.0.0.1', 46385)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "build/bdist.linux-x86_64/egg/prometheus_client/exposition.py", line 76, in do_GET
    self.wfile.write(generate_latest(core.REGISTRY))
  File "build/bdist.linux-x86_64/egg/prometheus_client/exposition.py", line 55, in generate_latest
    for metric in registry.collect():
  File "build/bdist.linux-x86_64/egg/prometheus_client/core.py", line 54, in collect
    for metric in collector.collect():
  File "jenkins_exporter.py", line 34, in collect
    self._get_metrics(name, job)
  File "jenkins_exporter.py", line 94, in _get_metrics
    status_data = job[status] or {}
KeyError: 'lastBuild'

A simple one liner can fix this up, if you are fine I can generate a pull request.

fix: In _get_metrics just adding this fixes the issue
if status in job.keys():

**Comment by vanesa** [comment]
sure, go ahead!
